export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import './globals.css'
import { Toaster } from 'sonner'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
      <Toaster position="top-center" /> 
      </body>
    </html>
  )
}
